// <auto-generated />
namespace ATM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changethenametypeofoperations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changethenametypeofoperations));
        
        string IMigrationMetadata.Id
        {
            get { return "201901021528496_Change the name type of operations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
